import { ModelOption } from '../types';

export const DEFAULT_WORKER_URL = 'https://ai-inference.thisisformysisternig.workers.dev';
export const DEFAULT_WS_URL = 'wss://ai-inference.thisisformysisternig.workers.dev';

export const WORKER_ENDPOINTS = [
  { path: 'GET /', label: 'Documentation', category: 'system', desc: 'API metadata and catalog' },
  { path: 'GET /camera', label: 'Camera Client', category: 'camera', desc: 'Browser camera client for live face scanning' },
  { path: 'POST /text', label: 'Text Generation', category: 'text', desc: 'Generate natural text and chat completions' },
  { path: 'POST /ai/reason', label: 'Deep Reasoning', category: 'text', desc: 'Step-by-step analytical reasoning' },
  { path: 'POST /ai/function-call', label: 'Function Calling', category: 'text', desc: 'Structured tool execution & function schema' },
  { path: 'POST /image/generate', label: 'Image Generate', category: 'vision', desc: 'High-res image generation via FLUX / Phoenix' },
  { path: 'POST /image/edit', label: 'Image Edit', category: 'vision', desc: 'Multi-reference image editing' },
  { path: 'POST /image/face', label: 'Face Studio', category: 'vision', desc: '33 face presets + custom prompts' },
  { path: 'GET /image/face/presets', label: 'Face Presets', category: 'vision', desc: 'Catalog of 33 facial transformations' },
  { path: 'POST /image/inpaint', label: 'Inpainting', category: 'vision', desc: 'Targeted image replacement with mask' },
  { path: 'POST /image/analyze', label: 'Image Analyze', category: 'vision', desc: 'Vision QA with Llama 3.2 11B' },
  { path: 'POST /video/generate', label: 'Text to Video', category: 'video', desc: 'Flux-3 video generation' },
  { path: 'POST /video/from-image', label: 'Image to Video', category: 'video', desc: 'Animate still photos to video' },
  { path: 'POST /video/analyze', label: 'Video Analyze', category: 'video', desc: 'Frame-by-frame video comparison & QA' },
  { path: 'POST /voice/transcribe', label: 'Transcribe', category: 'voice', desc: 'Speech-to-text with Whisper / Nova-3' },
  { path: 'POST /voice/translate', label: 'Voice Translate', category: 'voice', desc: 'Audio translation with optional TTS' },
  { path: 'POST /translate', label: 'Text Translate', category: 'translate', desc: 'M2M-100 / IndicTrans2 multilingual translation' },
  { path: 'POST /voice/speak', label: 'Text to Speech', category: 'voice', desc: 'Aura-1 / Aura-2 ultra-natural voice synthesis' },
  { path: 'WS /voice/live', label: 'Live Voice Stream', category: 'voice', desc: 'Low-latency live voice translation WebSocket' },
  { path: 'WS /face/live', label: 'Live Camera Face', category: 'camera', desc: 'Live camera scanning via WebSocket' },
  { path: 'POST /ml/classify/text', label: 'Classify Text', category: 'ml', desc: 'Sentiment & topic classification' },
  { path: 'POST /ml/detect', label: 'Object Detection', category: 'ml', desc: 'DETR ResNet-50 vision object detection' },
  { path: 'POST /ml/embed', label: 'Embeddings', category: 'ml', desc: 'BGE & Google EmbeddingGemma vector representations' },
  { path: 'POST /ml/rerank', label: 'Document Rerank', category: 'ml', desc: 'BGE reranker for semantic relevance' },
  { path: 'GET /curriculum', label: 'Curriculum Catalog', category: 'education', desc: 'K-through-Doctoral curriculum index' },
  { path: 'POST /learn', label: 'AI Tutor', category: 'education', desc: 'Triple-check verified instructional engine' },
  { path: 'POST /knowledge/search', label: 'Knowledge Base', category: 'education', desc: 'Triple-checked verified subject search' },
  { path: 'POST /ml/lora', label: 'LoRA Inference', category: 'ml', desc: 'Custom fine-tuned LoRA adapters' },
];

export const AVAILABLE_MODELS: ModelOption[] = [
  {
    id: '@cf/meta/llama-3.1-8b-instruct-fast',
    name: 'Llama 3.1 8B Fast',
    category: 'text',
    provider: 'Meta',
    description: 'Fast, cost-effective model for general chat and reasoning',
    speed: 'Ultra-Fast',
    recommendedFor: 'Text, Chat, General Queries',
  },
  {
    id: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    name: 'Llama 3.3 70B Fast',
    category: 'text',
    provider: 'Meta',
    description: 'Flagship open weights model with state-of-the-art accuracy',
    speed: 'Fast',
    recommendedFor: 'Complex tasks, coding, writing',
  },
  {
    id: '@cf/deepseek/deepseek-r1-distill-qwen-32b',
    name: 'DeepSeek R1 Distill 32B',
    category: 'reason',
    provider: 'DeepSeek',
    description: 'Advanced mathematical & chain-of-thought reasoning',
    speed: 'Standard',
    recommendedFor: 'STEM, Logic, Reasoning',
  },
  {
    id: '@cf/openai/gpt-oss-20b',
    name: 'GPT-OSS 20B',
    category: 'reason',
    provider: 'OpenAI OSS',
    description: 'Specialized for structured generation and analysis',
    speed: 'Fast',
    recommendedFor: 'Function calling, structured output',
  },
  {
    id: '@cf/nvidia/nemotron-3-120b-a12b',
    name: 'NVIDIA Nemotron 3 120B',
    category: 'text',
    provider: 'NVIDIA',
    description: 'Enterprise grade model specialized for tool calling and accuracy',
    speed: 'Heavy',
    recommendedFor: 'Tool & Function calling',
  },
  {
    id: '@cf/ibm/granite-4.0-h-micro',
    name: 'IBM Granite 4.0 Micro',
    category: 'text',
    provider: 'IBM',
    description: 'Efficient enterprise micro-model for rapid inferences',
    speed: 'Ultra-Fast',
    recommendedFor: 'Fast routing & utility tasks',
  },
  {
    id: '@cf/black-forest-labs/flux-2-klein-4b',
    name: 'FLUX.2 Klein 4B',
    category: 'image',
    provider: 'Black Forest Labs',
    description: 'High-speed image generation with sharp compositions',
    speed: 'Fast',
    recommendedFor: 'Fast image generation',
  },
  {
    id: '@cf/black-forest-labs/flux-2-klein-9b',
    name: 'FLUX.2 Klein 9B (Ultra-HQ)',
    category: 'image',
    provider: 'Black Forest Labs',
    description: 'Maximum realism, photorealistic facial details and lighting',
    speed: 'Standard',
    recommendedFor: 'Ultra-realistic images & Face editing',
  },
  {
    id: '@cf/leonardo/phoenix-1.0',
    name: 'Leonardo Phoenix 1.0',
    category: 'image',
    provider: 'Leonardo',
    description: 'Creative and artistic visual styling with rich textures',
    speed: 'Standard',
    recommendedFor: 'Artistic visuals and creative prompts',
  },
  {
    id: '@cf/meta/llama-3.2-11b-vision-instruct',
    name: 'Llama 3.2 11B Vision',
    category: 'vision',
    provider: 'Meta',
    description: 'Multi-modal vision understanding, chart reading, and QA',
    speed: 'Fast',
    recommendedFor: 'Image QA, OCR, Analysis',
  },
  {
    id: '@cf/openai/whisper',
    name: 'OpenAI Whisper',
    category: 'voice',
    provider: 'OpenAI',
    description: 'Accurate speech-to-text transcription in 90+ languages',
    speed: 'Fast',
    recommendedFor: 'Voice transcription',
  },
  {
    id: '@cf/deepgram/nova-3',
    name: 'Deepgram Nova-3',
    category: 'voice',
    provider: 'Deepgram',
    description: 'Next-generation speech recognition with low latency',
    speed: 'Ultra-Fast',
    recommendedFor: 'Real-time audio transcription',
  },
  {
    id: '@cf/deepgram/aura-1',
    name: 'Deepgram Aura 1',
    category: 'tts',
    provider: 'Deepgram',
    description: 'Conversational voice synthesis with natural human cadence',
    speed: 'Ultra-Fast',
    recommendedFor: 'Text to speech synthesis',
  },
  {
    id: '@cf/deepgram/aura-2-en',
    name: 'Deepgram Aura 2 EN',
    category: 'tts',
    provider: 'Deepgram',
    description: 'Enhanced emotional range and natural intonation',
    speed: 'Ultra-Fast',
    recommendedFor: 'High quality narration',
  },
  {
    id: '@cf/meta/m2m100-1.2b',
    name: 'M2M-100 1.2B',
    category: 'translate',
    provider: 'Meta',
    description: 'Direct translation between 100 language pairs without English pivot',
    speed: 'Fast',
    recommendedFor: 'Multilingual translation',
  },
  {
    id: '@cf/ai4bharat/indictrans2-en-indic-1B',
    name: 'IndicTrans2 1B',
    category: 'translate',
    provider: 'AI4Bharat',
    description: 'Specialized for Indian and South Asian languages',
    speed: 'Fast',
    recommendedFor: 'Hindi, Bengali, Tamil, etc.',
  },
  {
    id: '@cf/black-forest-labs/flux-3-video',
    name: 'FLUX.3 Video',
    category: 'video',
    provider: 'Black Forest Labs',
    description: 'High coherence text-to-video generation',
    speed: 'Heavy',
    recommendedFor: 'Short dynamic video clips',
  },
  {
    id: 'alibaba/wan-2.7-i2v',
    name: 'Wan 2.7 Image-to-Video',
    category: 'video',
    provider: 'Alibaba',
    description: 'Image animation into realistic camera motions',
    speed: 'Heavy',
    recommendedFor: 'Photo animation',
  },
  {
    id: '@cf/runwayml/stable-diffusion-v1-5-inpainting',
    name: 'Stable Diffusion Inpainting',
    category: 'image',
    provider: 'RunwayML',
    description: 'Precision mask-based object replacement & erase',
    speed: 'Fast',
    recommendedFor: 'Inpainting & repair',
  },
  {
    id: '@cf/huggingface/distilbert-sst-2-int8',
    name: 'DistilBERT SST-2',
    category: 'ml',
    provider: 'HuggingFace',
    description: 'Ultra-fast sentiment and polarity classification',
    speed: 'Ultra-Fast',
    recommendedFor: 'Sentiment analysis',
  },
  {
    id: '@cf/meta/detr-resnet-50',
    name: 'DETR ResNet-50',
    category: 'ml',
    provider: 'Meta',
    description: 'End-to-end transformer for object detection',
    speed: 'Fast',
    recommendedFor: 'Bounding box detection',
  },
  {
    id: '@cf/baai/bge-base-en-v1.5',
    name: 'BGE Base EN v1.5',
    category: 'ml',
    provider: 'BAAI',
    description: 'Dense 768-dimensional text embedding vectors',
    speed: 'Ultra-Fast',
    recommendedFor: 'Vector search & RAG',
  },
  {
    id: '@cf/google/embeddinggemma-300m',
    name: 'Google EmbeddingGemma 300M',
    category: 'ml',
    provider: 'Google',
    description: 'Compact embedding model built on Gemma architecture',
    speed: 'Ultra-Fast',
    recommendedFor: 'High-density vector embeddings',
  },
  {
    id: '@cf/baai/bge-reranker-base',
    name: 'BGE Reranker Base',
    category: 'ml',
    provider: 'BAAI',
    description: 'Cross-encoder scoring for document relevance',
    speed: 'Fast',
    recommendedFor: 'Semantic document reranking',
  },
];

export const FACE_PRESETS: Record<string, string> = {
  smile: 'Take the person in image 0 and make them smile warmly with a natural genuine expression. Keep everything else exactly the same. Only change the facial expression. Photorealistic ultra-detailed no artifacts.',
  big_smile: 'Take the person in image 0 and make them laugh with a big joyful smile showing teeth. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  frown: 'Take the person in image 0 and make them frown with a subtle unhappy expression. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  look_left: 'Take the person in image 0 and make them look to their left while keeping the same head position. Keep everything else the same. Only change the eye direction. Photorealistic ultra-detailed.',
  look_right: 'Take the person in image 0 and make them look to their right while keeping the same head position. Keep everything else the same. Only change the eye direction. Photorealistic ultra-detailed.',
  look_up: 'Take the person in image 0 and make them look upward while keeping the same head position. Keep everything else the same. Only change the eye direction. Photorealistic ultra-detailed.',
  look_down: 'Take the person in image 0 and make them look downward while keeping the same head position. Keep everything else the same. Only change the eye direction. Photorealistic ultra-detailed.',
  close_eyes: 'Take the person in image 0 and make them close their eyes gently. Keep everything else the same. Only change the eye state. Photorealistic ultra-detailed.',
  open_eyes: 'Take the person in image 0 and make them open their eyes wide with an alert expression. Keep everything else the same. Only change the eye state. Photorealistic ultra-detailed.',
  wink: 'Take the person in image 0 and make them wink with one eye closed playfully. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  angry: 'Take the person in image 0 and make them look angry with a furrowed brow and tense expression. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  sad: 'Take the person in image 0 and make them look sad with a melancholic expression. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  surprised: 'Take the person in image 0 and make them look surprised with wide eyes and open mouth. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  fearful: 'Take the person in image 0 and make them look fearful with wide eyes and tense expression. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  disgusted: 'Take the person in image 0 and make them look disgusted with a wrinkled nose. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  neutral: 'Take the person in image 0 and give them a calm neutral expression. Keep everything else the same. Only change the facial expression. Photorealistic ultra-detailed.',
  older: 'Take the person in image 0 and make them look 20 years older with natural aging. Keep the same identity clothing background and pose. Photorealistic ultra-detailed.',
  younger: 'Take the person in image 0 and make them look 15 years younger with smooth skin. Keep the same identity clothing background and pose. Photorealistic ultra-detailed.',
  change_hair: 'Take the person in image 0 and give them a different hairstyle while keeping everything else the same. Photorealistic ultra-detailed.',
  long_hair: 'Take the person in image 0 and give them long flowing hair while keeping everything else the same. Photorealistic ultra-detailed.',
  short_hair: 'Take the person in image 0 and give them short hair while keeping everything else the same. Photorealistic ultra-detailed.',
  blonde_hair: 'Take the person in image 0 and give them blonde hair while keeping everything else the same. Photorealistic ultra-detailed.',
  black_hair: 'Take the person in image 0 and give them black hair while keeping everything else the same. Photorealistic ultra-detailed.',
  beard: 'Take the person in image 0 and add a natural beard while keeping everything else the same. Photorealistic ultra-detailed.',
  remove_beard: 'Take the person in image 0 and remove any facial hair making them clean-shaven while keeping everything else the same. Photorealistic ultra-detailed.',
  glasses: 'Take the person in image 0 and add stylish glasses while keeping everything else the same. Photorealistic ultra-detailed.',
  remove_glasses: 'Take the person in image 0 and remove any glasses while keeping everything else the same. Photorealistic ultra-detailed.',
  change_background: 'Take the person in image 0 and place them in a new background setting. Keep the same person same clothing same pose. Photorealistic ultra-detailed.',
  professional: 'Take the person in image 0 and dress them in professional business attire while keeping the same person same face same pose. Photorealistic ultra-detailed.',
  casual: 'Take the person in image 0 and dress them in casual clothing while keeping the same person same face same pose. Photorealistic ultra-detailed.',
  night: 'Take the person in image 0 and change the lighting to nighttime while keeping the same person same clothing same pose. Photorealistic ultra-detailed.',
  day: 'Take the person in image 0 and change the lighting to bright daytime while keeping the same person same clothing same pose. Photorealistic ultra-detailed.',
  black_white: 'Take the person in image 0 and convert to a classic black and white photograph while keeping the same person same pose. Photorealistic ultra-detailed.',
  vintage: 'Take the person in image 0 and make it look like a vintage photograph from the 1950s while keeping the same person. Photorealistic ultra-detailed.',
};

export const POPULAR_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish (Español)' },
  { code: 'fr', name: 'French (Français)' },
  { code: 'de', name: 'German (Deutsch)' },
  { code: 'zh', name: 'Chinese (中文)' },
  { code: 'ja', name: 'Japanese (日本語)' },
  { code: 'hi', name: 'Hindi (हिन्दी)' },
  { code: 'ar', name: 'Arabic (العربية)' },
  { code: 'pt', name: 'Portuguese (Português)' },
  { code: 'ru', name: 'Russian (Русский)' },
  { code: 'ko', name: 'Korean (한국어)' },
  { code: 'it', name: 'Italian (Italiano)' },
  { code: 'nl', name: 'Dutch (Nederlands)' },
  { code: 'tr', name: 'Turkish (Türkçe)' },
  { code: 'pl', name: 'Polish (Polski)' },
  { code: 'vi', name: 'Vietnamese (Tiếng Việt)' },
];
