import { AppSettings } from '../types';
import { DEFAULT_WORKER_URL } from './models';

export interface ParameterMeta {
  key: keyof AppSettings;
  label: string;
  category: 'text' | 'vision' | 'video' | 'voice' | 'translate' | 'ml' | 'resilience';
  endpoint: string;
  description: string;
  effect: string;
  defaultValue: any;
  type: 'number' | 'string' | 'boolean' | 'select' | 'slider';
  min?: number;
  max?: number;
  step?: number;
  options?: { value: any; label: string }[];
  unit?: string;
}

export const DEFAULT_APP_SETTINGS: AppSettings = {
  baseUrl: DEFAULT_WORKER_URL,
  // Text & Reasoning
  defaultTextModel: '@cf/meta/llama-3.1-8b-instruct-fast',
  defaultReasonModel: '@cf/deepseek/deepseek-r1-distill-qwen-32b',
  temperature: 0.7,
  topP: 0.9,
  maxTokens: 2048,
  systemPrompt: 'You are Trill AI, an intelligent, helpful, and concise multi-modal assistant.',
  stream: true,
  streamSpeed: 'fast',

  // Vision & Image
  defaultVisionModel: '@cf/meta/llama-3.2-11b-vision-instruct',
  defaultImageModel: '@cf/black-forest-labs/flux-2-klein-4b',
  imageWidth: 1024,
  imageHeight: 1024,
  imageGuidance: 3.5,
  imageSteps: 20,
  imageStrength: 0.75,
  defaultFacePreset: 'smile',

  // Video
  videoDuration: 4,
  videoResolution: '720p',
  videoFps: 24,

  // Voice & Audio
  defaultVoiceModel: '@cf/deepgram/aura-2-en',
  voiceTtsProfile: 'aura-asteria-en',
  sttLanguage: 'en',
  voiceTranslateTts: true,
  autoPlayAudio: true,

  // Translation
  defaultSourceLang: 'en',
  defaultTargetLang: 'es',

  // ML & Education
  defaultEmbedModel: '@cf/baai/bge-base-en-v1.5',
  educationLevel: 'Undergraduate / College',

  // Network & Resilience
  timeoutSeconds: 45,
  autoRetryAttempts: 2,
  soundEnabled: true,
  autoSaveHistory: true,
};

export const MODEL_PARAMETER_CATALOG: ParameterMeta[] = [
  // Text & Reasoning
  {
    key: 'temperature',
    label: 'Temperature (Sampling Randomness)',
    category: 'text',
    endpoint: 'POST /text, POST /ai/reason, POST /ai/function-call',
    description: 'Controls stochastic randomness in model token sampling.',
    effect: 'Lower values (0.1–0.4) yield deterministic, focused, and mathematically factual answers. Higher values (0.7–1.2) stimulate creative diversity and linguistic variation.',
    defaultValue: 0.7,
    type: 'slider',
    min: 0.0,
    max: 1.5,
    step: 0.05,
    unit: '',
  },
  {
    key: 'topP',
    label: 'Top-P (Nucleus Sampling)',
    category: 'text',
    endpoint: 'POST /text, POST /ai/reason',
    description: 'Probability threshold mass for token candidate selection.',
    effect: 'Filters out low-probability tail tokens. Setting to 0.8 evaluates only top 80% likely words, preventing rare hallucinated tokens while maintaining fluency.',
    defaultValue: 0.9,
    type: 'slider',
    min: 0.1,
    max: 1.0,
    step: 0.05,
    unit: '',
  },
  {
    key: 'maxTokens',
    label: 'Max Generation Tokens',
    category: 'text',
    endpoint: 'POST /text, POST /ai/reason, POST /ai/function-call',
    description: 'Upper bound limit on total completion tokens returned.',
    effect: 'Prevents runaway generation. Use 512 for concise answers, or up to 4096 for extensive essays, code implementations, or multi-step logic.',
    defaultValue: 2048,
    type: 'slider',
    min: 128,
    max: 4096,
    step: 128,
    unit: 'tokens',
  },
  {
    key: 'stream',
    label: 'Real-Time Streaming Engine',
    category: 'text',
    endpoint: 'POST /text, POST /ai/reason',
    description: 'Enables real-time chunked token streaming as output arrives from the API.',
    effect: 'Delivers immediate progressive visual output into the interface with animated cadence and velocity metrics, eliminating blank waiting screens.',
    defaultValue: true,
    type: 'boolean',
  },
  {
    key: 'streamSpeed',
    label: 'Stream Rendering Cadence',
    category: 'text',
    endpoint: 'UI Stream Engine',
    description: 'Determines the visual typing animation speed.',
    effect: 'Fast: ~60 tok/s for brisk reading. Normal: ~35 tok/s natural human cadence. Slow: ~18 tok/s for study. Instant: immediate burst rendering.',
    defaultValue: 'fast',
    type: 'select',
    options: [
      { value: 'fast', label: 'Fast (60 tok/s smooth)' },
      { value: 'normal', label: 'Normal (35 tok/s natural)' },
      { value: 'slow', label: 'Slow (18 tok/s study)' },
      { value: 'instant', label: 'Instant (No delay)' },
    ],
  },
  {
    key: 'systemPrompt',
    label: 'Default System Instruction',
    category: 'text',
    endpoint: 'POST /text',
    description: 'Guiding steering prompt prepended to conversational turns.',
    effect: 'Sets foundational personality, domain role, formatting constraints, and security safety guidelines for the LLM.',
    defaultValue: 'You are Trill AI, an intelligent, helpful, and concise multi-modal assistant.',
    type: 'string',
  },

  // Vision & Image
  {
    key: 'imageWidth',
    label: 'Image Width (px)',
    category: 'vision',
    endpoint: 'POST /image/generate',
    description: 'Horizontal pixel dimension for FLUX.2 Klein / Leonardo Phoenix.',
    effect: 'Sets canvas width. 1024 produces high-res square or landscape output; 768 or 512 speeds up generation time.',
    defaultValue: 1024,
    type: 'select',
    options: [
      { value: 512, label: '512 px (Fastest preview)' },
      { value: 768, label: '768 px (Balanced)' },
      { value: 1024, label: '1024 px (High-Def standard)' },
      { value: 1280, label: '1280 px (Widescreen HD)' },
    ],
  },
  {
    key: 'imageHeight',
    label: 'Image Height (px)',
    category: 'vision',
    endpoint: 'POST /image/generate',
    description: 'Vertical pixel dimension for generated images.',
    effect: 'Sets canvas height. Pair with 1024 for 1:1 square, or 768/1280 for portrait or cinematic aspect ratios.',
    defaultValue: 1024,
    type: 'select',
    options: [
      { value: 512, label: '512 px' },
      { value: 768, label: '768 px' },
      { value: 1024, label: '1024 px (Standard)' },
      { value: 1280, label: '1280 px (Tall portrait)' },
    ],
  },
  {
    key: 'imageGuidance',
    label: 'CFG Guidance Scale',
    category: 'vision',
    endpoint: 'POST /image/generate, POST /image/edit',
    description: 'Classifier-Free Guidance weight for prompt adherence.',
    effect: 'Scale of 1.0–10.0. Higher values (4.5–7.0) force the model to adhere strictly to keywords; lower values (2.5–3.5) yield softer, artistic, natural compositions.',
    defaultValue: 3.5,
    type: 'slider',
    min: 1.0,
    max: 10.0,
    step: 0.5,
    unit: '',
  },
  {
    key: 'imageSteps',
    label: 'Diffusion Denoising Steps',
    category: 'vision',
    endpoint: 'POST /image/generate',
    description: 'Number of iterative sampling steps in latent diffusion.',
    effect: 'Higher steps (25–40) refine fine hair, skin textures, and specular reflections; lower steps (8–16) generate in under 3 seconds.',
    defaultValue: 20,
    type: 'slider',
    min: 4,
    max: 50,
    step: 2,
    unit: 'steps',
  },
  {
    key: 'imageStrength',
    label: 'Edit & Inpaint Strength',
    category: 'vision',
    endpoint: 'POST /image/edit, POST /image/inpaint',
    description: 'Modification intensity for reference image edits and inpainting.',
    effect: 'Low values (0.2–0.4) gently tweak colors and lighting while retaining structure. High values (0.75–0.95) allow drastic element changes.',
    defaultValue: 0.75,
    type: 'slider',
    min: 0.1,
    max: 1.0,
    step: 0.05,
    unit: '',
  },
  {
    key: 'defaultFacePreset',
    label: 'Default Face Studio Preset',
    category: 'vision',
    endpoint: 'POST /image/face',
    description: 'Default facial transformation selected when entering Face Studio.',
    effect: 'Applies predefined prompt engineering for expression, age, hair, or lighting changes to portrait photos.',
    defaultValue: 'smile',
    type: 'select',
    options: [
      { value: 'smile', label: 'Warm Smile' },
      { value: 'big_smile', label: 'Joyful Laugh' },
      { value: 'younger', label: '15 Years Younger' },
      { value: 'older', label: '20 Years Older' },
      { value: 'professional', label: 'Business Attire' },
      { value: 'glasses', label: 'Stylish Glasses' },
      { value: 'neutral', label: 'Calm Neutral' },
    ],
  },

  // Video Dynamics
  {
    key: 'videoDuration',
    label: 'Video Clip Duration',
    category: 'video',
    endpoint: 'POST /video/generate, POST /video/from-image',
    description: 'Length in seconds for synthesized video clips.',
    effect: 'Controls temporal sequence length. 4 seconds provides optimum coherence for FLUX.3 Video and Wan 2.7 image-to-video animations.',
    defaultValue: 4,
    type: 'slider',
    min: 2,
    max: 8,
    step: 1,
    unit: 'seconds',
  },
  {
    key: 'videoResolution',
    label: 'Video Output Resolution',
    category: 'video',
    endpoint: 'POST /video/generate',
    description: 'Spatial pixel resolution of rendered video files.',
    effect: '720p offers crisp HD playback with rapid render times; 1080p delivers high-fidelity presentation; 480p optimizes for quick mobile loading.',
    defaultValue: '720p',
    type: 'select',
    options: [
      { value: '480p', label: '480p Standard (Fast render)' },
      { value: '720p', label: '720p High Definition (Recommended)' },
      { value: '1080p', label: '1080p Full HD (Crisp quality)' },
    ],
  },
  {
    key: 'videoFps',
    label: 'Video Framerate (FPS)',
    category: 'video',
    endpoint: 'POST /video/generate',
    description: 'Playback frequency of temporal video frames.',
    effect: '24 FPS provides cinematic motion blur; 30 FPS provides smooth modern video fluidity.',
    defaultValue: 24,
    type: 'select',
    options: [
      { value: 16, label: '16 FPS (Stylized motion)' },
      { value: 24, label: '24 FPS (Cinematic standard)' },
      { value: 30, label: '30 FPS (Smooth playback)' },
    ],
  },

  // Voice & Audio
  {
    key: 'voiceTtsProfile',
    label: 'Deepgram Aura Voice Profile',
    category: 'voice',
    endpoint: 'POST /voice/speak',
    description: 'Speaker vocal identity, pitch, and timbre for Aura-1 / Aura-2 speech.',
    effect: 'Asteria: warm, clear female narrator. Luna: bright, upbeat conversational. Stella: professional calm. Zeus / Orion: deep, resonant male tones.',
    defaultValue: 'aura-asteria-en',
    type: 'select',
    options: [
      { value: 'aura-asteria-en', label: 'Asteria (Warm & Clear Narration - Female)' },
      { value: 'aura-luna-en', label: 'Luna (Bright & Conversational - Female)' },
      { value: 'aura-stella-en', label: 'Stella (Calm & Professional - Female)' },
      { value: 'aura-athena-en', label: 'Athena (Authoritative & Crisp - Female)' },
      { value: 'aura-zeus-en', label: 'Zeus (Deep & Authoritative - Male)' },
      { value: 'aura-orion-en', label: 'Orion (Smooth & Resonant - Male)' },
    ],
  },
  {
    key: 'sttLanguage',
    label: 'Transcription Language Code',
    category: 'voice',
    endpoint: 'POST /voice/transcribe',
    description: 'Audio speech recognition language hint for Whisper and Nova-3.',
    effect: 'Provides phoneme dictionary bias. Selecting "en" ensures swift English transcription; "auto" runs language detection.',
    defaultValue: 'en',
    type: 'select',
    options: [
      { value: 'en', label: 'English (en)' },
      { value: 'auto', label: 'Auto-Detect' },
      { value: 'es', label: 'Spanish (es)' },
      { value: 'fr', label: 'French (fr)' },
      { value: 'de', label: 'German (de)' },
      { value: 'hi', label: 'Hindi (hi)' },
      { value: 'zh', label: 'Chinese (zh)' },
      { value: 'ja', label: 'Japanese (ja)' },
    ],
  },
  {
    key: 'voiceTranslateTts',
    label: 'Auto-Speak Spoken Translations',
    category: 'voice',
    endpoint: 'POST /voice/translate',
    description: 'Automatically trigger Aura text-to-speech for translated audio.',
    effect: 'When active, vocal translations automatically stream the translated phrase in spoken audio in addition to text.',
    defaultValue: true,
    type: 'boolean',
  },
  {
    key: 'autoPlayAudio',
    label: 'Auto-Play Synthesized Speech',
    category: 'voice',
    endpoint: 'POST /voice/speak',
    description: 'Instantly play audio playback when synthesis completes.',
    effect: 'Plays synthesized MP3/WAV audio through the browser without requiring a manual click on the play button.',
    defaultValue: true,
    type: 'boolean',
  },

  // Translation & Education
  {
    key: 'defaultSourceLang',
    label: 'Default Source Translation Language',
    category: 'translate',
    endpoint: 'POST /translate, POST /voice/translate',
    description: 'Origin language code for Meta M2M-100 / IndicTrans2.',
    effect: 'Preselects the source input language dropdown across translation interfaces.',
    defaultValue: 'en',
    type: 'string',
  },
  {
    key: 'defaultTargetLang',
    label: 'Default Target Translation Language',
    category: 'translate',
    endpoint: 'POST /translate, POST /voice/translate',
    description: 'Destination language code for Meta M2M-100 / IndicTrans2.',
    effect: 'Preselects the target translation output language dropdown.',
    defaultValue: 'es',
    type: 'string',
  },
  {
    key: 'educationLevel',
    label: 'Curriculum & AI Tutor Level',
    category: 'ml',
    endpoint: 'POST /learn, POST /knowledge/search',
    description: 'Target pedagogical rigor and academic depth for the triple-checked AI tutor.',
    effect: 'Controls vocabulary difficulty, theoretical depth, and reference complexity from Elementary to Doctoral.',
    defaultValue: 'Undergraduate / College',
    type: 'select',
    options: [
      { value: 'Elementary (Grades 1-5)', label: 'Elementary (Grades 1-5)' },
      { value: 'Middle School (Grades 6-8)', label: 'Middle School (Grades 6-8)' },
      { value: 'High School (Grades 9-12)', label: 'High School (Grades 9-12)' },
      { value: 'Undergraduate / College', label: 'Undergraduate / College' },
      { value: 'Graduate / Professional', label: 'Graduate / Professional' },
      { value: 'Doctoral / Research', label: 'Doctoral / Research' },
    ],
  },
  {
    key: 'defaultEmbedModel',
    label: 'Dense Vector Embedding Model',
    category: 'ml',
    endpoint: 'POST /ml/embed',
    description: 'Vector representation model for semantic search and classification.',
    effect: 'BGE Base v1.5 outputs 768-dim vectors optimized for search; Google EmbeddingGemma provides 300M parameter token representations.',
    defaultValue: '@cf/baai/bge-base-en-v1.5',
    type: 'select',
    options: [
      { value: '@cf/baai/bge-base-en-v1.5', label: 'BGE Base EN v1.5 (768-dim)' },
      { value: '@cf/google/embeddinggemma-300m', label: 'Google EmbeddingGemma 300M' },
    ],
  },

  // Resilience & Gateway
  {
    key: 'baseUrl',
    label: 'Cloudflare Worker Base URL',
    category: 'resilience',
    endpoint: 'Global Gateway',
    description: 'The root URL of the Cloudflare Workers AI inference service.',
    effect: 'Routes all inference requests, media uploads, and WebSockets to the specified worker instance.',
    defaultValue: DEFAULT_WORKER_URL,
    type: 'string',
  },
  {
    key: 'timeoutSeconds',
    label: 'Request Timeout (seconds)',
    category: 'resilience',
    endpoint: 'All Endpoints',
    description: 'Network timeout threshold before canceling hung requests.',
    effect: 'Protects against hanging connections on slow networks. Triggers auto-retry if configured.',
    defaultValue: 45,
    type: 'slider',
    min: 15,
    max: 120,
    step: 5,
    unit: 'seconds',
  },
  {
    key: 'autoRetryAttempts',
    label: 'Auto-Retry Attempts on Failure',
    category: 'resilience',
    endpoint: 'All Endpoints',
    description: 'Automatic retry attempts with exponential backoff on network drops or HTTP 500/429.',
    effect: '0 disables retries. 1–4 attempts sequentially retry failed calls after 1s, 2s, 4s delays, improving reliability.',
    defaultValue: 2,
    type: 'slider',
    min: 0,
    max: 4,
    step: 1,
    unit: 'retries',
  },
  {
    key: 'autoSaveHistory',
    label: 'Auto-Save Inferences to Local History',
    category: 'resilience',
    endpoint: 'Client Storage',
    description: 'Persists completed inference outputs and token counts in browser storage.',
    effect: 'Enables quick search, filter, prompt re-injection, and JSON export via the slide-over history drawer.',
    defaultValue: true,
    type: 'boolean',
  },
  {
    key: 'soundEnabled',
    label: 'Audio Chime Feedback',
    category: 'resilience',
    endpoint: 'Client Audio',
    description: 'Plays a subtle audio notification when generation completes.',
    effect: 'Provides audio cue when long vision or reasoning inferences finish while working in another window.',
    defaultValue: true,
    type: 'boolean',
  },
];
